### ISSUE TITLE
Node environemnt error for version 6.10.3

### ISSUE THREAD

**Issue by vasukumar169** [yaacov/node-modbus-serial#198] opened 2018-04-16 12:54 UTC
Hi,

I am unable to setup the environment on the version 6.10.3.

It is working fine on 8.x version.

Could you tell , will this package supports 6.10.3 version or  it only supports 8.x version.

**Comment by yaacov** [comment] 2018-04-16 13:02
I do not know, currently we only check against v9.8.0,
I do not know of any reason it will not work with v6.x,
If you find the reason for it not working, please comment here, so we can fix it.

**Comment by yaacov** [comment] 2018-04-26 15:16
looks like #199

**Comment by yaacov** [comment] 2018-04-26 15:30
closing, duplicate of #199

**Closed by yaacov** 2018-04-26 15:30 UTC
